services:
  app:
    build: ./app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./db/00000073909.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: